create or replace PROCEDURE CREATE_TEAM_VIEW
IS
BEGIN
    EXECUTE IMMEDIATE
    'CREATE OR REPLACE VIEW TEAM_VIEW
    AS
    SELECT
        TEAM.CODE,
        TEAM.LOGO_PATH_CODE,
        LOGO_PATH.PATH AS LOGO_PATH,
        LOGO_PATH.NAME AS LOGO_NAME,
        TEAM.LOGO,
        TEAM.NAME,
        TEAM.MEMBER_CODE,
        MEMBER.NAME AS MEMBER_NAME,
        MEMBER.PHONE AS MEMBER_PHONE,
        TEAM.HOMETOWN_CODE,
        HOMETOWN.NAME AS HOMETOWN_NAME,
        TEAM.OUTLINE,
        TEAM.CONTENT,
        TEAM.REG_DATE,
        TEAM.MOD_DATE,
        TEAM.DEL_DATE
    FROM
        TEAM LEFT JOIN LOGO_PATH
        ON TEAM.LOGO_PATH_CODE = LOGO_PATH.CODE
        LEFT JOIN MEMBER
        ON TEAM.MEMBER_CODE = MEMBER.CODE
        LEFT JOIN HOMETOWN 
        ON HOMETOWN_CODE = HOMETOWN.CODE
    WITH READ ONLY';
END;