SELECT * FROM BOARD_KIND;
UPDATE BOARD_KIND SET NAME = '공지사항' WHERE CODE = 1002;
UPDATE BOARD_KIND SET NAME = '자유게시판' WHERE CODE = 1003;
UPDATE BOARD_KIND SET NAME = '홍보게시판' WHERE CODE = 1004;
INSERT INTO BOARD_KIND VALUES (BOARD_KIND_CODE.NEXTVAL, '문의하기', DEFAULT, NULL, NULL);
COMMIT;